version: '3'
services:
  dnsmasq:
    image: jpillora/dnsmasq
    ports:
    - 53:53/udp
    - 54:54/udp
    - 54:54/tcp
    - 5380:8080/tcp
    volumes:
    - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      HTTP_USER:
      HTTP_PASS:
    restart: unless-stopped
  squid:
    image: datadog/squid
    restart: unless-stopped
    volumes:
    - ./squid/cache:/var/spool/squid