version: '3'
services:
  tftpd-hpa:
    image: jumanjiman/tftp-hpa
    ports:
    - 69:69/udp
    restart: unless-stopped
    volumes:
    - ./tftp-hpa/tftpboot:/tftpboot:ro

  nfs:
    image: outstand/nfs-client
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
    - ./nfs/isos:/mnt/host
    environment:
    # change this with local ip
    - SERVER: 172.16.0.10
    - SHARE: movies
    - MOUNT_OPTIONS: "ro,async,no_subtree_check,all_squash"
    - FSTYPE: nfs4
    - MOUNTPOINT: /mnt/host

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped