version: '3'
services:
  dnsmasq:
    image: jpillora/dnsmasq
    ports:
    - 172.16.0.1:53:53/udp
    - 172.16.0.1:53:53/tcp
    - 172.16.0.1:67:67/udp
    network_mode: "host"
    privileged: true
    volumes:
    - /etc/resolv.conf:/etc/resolv.conf:ro
    - ./flink/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
    - ./flink/dnsmasq/fnodes:/etc/fnodes:ro
    - ./flink/dnsmasq/dnsmasq.leases:/tmp/dnsmasq.leases
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      HTTP_USER:
      HTTP_PASS:
    restart: unless-stopped
  squid:
    image: sameersbn/squid:latest
    ports:
    - 3128:3128
    network_mode: "host"
    restart: unless-stopped
    volumes:
    - ./flink/squid/conf/squid.conf:/etc/squid/squid.conf
    - ./flink/squid/conf/squid.acl.custom:/etc/squid/squid.acl.custom
    - ./flink/squid/conf/squid.refreshpatterns.custom:/etc/squid/squid.refreshpatterns.custom
    - ./flink/squid/conf/errorpage.css:/etc/squid/errorpage.css
    - ./flink/squid/conf/blocks.files.acl:/etc/squid/blocks.files.acl
    - ./flink/squid/cache:/var/spool/squid
