version: '3'
services:
  dnsmasq:
    image: jpillora/dnsmasq
    ports:
    - 172.16.0.1:53:53/udp
    - 172.16.0.1:53:53/tcp
    - 172.16.0.1:67:67/udp
    network_mode: "host"
    volumes:
    - /etc/resolv.conf:/etc/resolv.conf:ro
    - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
    - ./dnsmasq/fnodes:/etc/fnodes:ro
    - ./dnsmasq/dnsmasq.leases:/tmp/dnsmasq.leases
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      HTTP_USER:
      HTTP_PASS:
    restart: unless-stopped
  squid:
    image: datadog/squid
    restart: unless-stopped
    volumes:
    - ./squid/cache:/var/spool/squid
