version: '3'
services:
  tftpd-hpa:
    image: jumanjiman/tftp-hpa
    network_mode: host
    ports:
    - 69:69/udp
    restart: unless-stopped
    volumes:
    - ./fnode/tftp-hpa/tftpboot:/tftpboot:ro

  nfs:
    image: outstand/nfs-client
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
    - ./fnode/tftp-hpa/tftpboot/isos:/mnt/host:ro
    environment:
      SERVER:
      SHARE: isos
      MOUNT_OPTIONS: "ro,async,no_subtree_check,all_squash"
      FSTYPE: nfs3
      MOUNTPOINT: /mnt/host

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
